name: Run Tests for backend in lab2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Change directory to lab2/backend
      - name: Set working directory to lab2/backend
        working-directory: lab2/backend
        run: pwd # Print the current directory for debugging

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('lab2/backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run tests
      - name: Run tests in backend
        working-directory: lab2/backend
        run: ./mvnw test
